import logging
from collections.abc import Sequence
from dataclasses import dataclass
from datetime import UTC, datetime
from hashlib import sha256
from pathlib import PurePosixPath
from typing import Any, Protocol
from uuid import UUID, uuid4

from fastapi import HTTPException, status
from httpx import HTTPError
from postgrest.exceptions import APIError
from supabase import Client

from app.schemas import CourseMapConcept, CourseMapResponse, CourseProgressResponse, CourseSummary, CreateCourseRequest, CreateSourceRequest, SourceSummary, SourceUploadTarget
from app.settings import get_settings
from app.supabase import get_service_client


logger = logging.getLogger(__name__)


class CourseRepository(Protocol):
    name: str

    def create_source(self, owner_id: UUID, request: CreateSourceRequest) -> SourceUploadTarget: ...

    def complete_source(self, owner_id: UUID, source_id: UUID) -> SourceSummary: ...

    def create_course(self, owner_id: UUID, request: CreateCourseRequest) -> CourseSummary: ...

    def list_courses(self, owner_id: UUID) -> list[CourseSummary]: ...

    def get_course(self, owner_id: UUID, course_id: UUID) -> CourseSummary: ...

    def course_map(self, owner_id: UUID, course_id: UUID) -> CourseMapResponse: ...

    def course_progress(self, owner_id: UUID, course_id: UUID) -> CourseProgressResponse: ...

    def regenerate_course(self, owner_id: UUID, course_id: UUID) -> CourseSummary: ...


@dataclass
class SourceRecord:
    id: UUID
    owner_id: UUID
    filename: str
    storage_path: str
    status: str


@dataclass
class CourseRecord:
    id: UUID
    owner_id: UUID
    title: str
    goal: str
    source_ids: list[UUID]
    status: str
    active_version: int
    updated_at: datetime


class MemoryCourseRepository:
    """Development-only adapter retained for isolated local tests."""

    name = "memory"

    def __init__(self) -> None:
        self.sources: dict[UUID, SourceRecord] = {}
        self.courses: dict[UUID, CourseRecord] = {}

    def create_source(self, owner_id: UUID, request: CreateSourceRequest) -> SourceUploadTarget:
        source_id = uuid4()
        safe_name = PurePosixPath(request.filename).name
        storage_path = f"{owner_id}/{source_id}/{safe_name}"
        self.sources[source_id] = SourceRecord(source_id, owner_id, safe_name, storage_path, "uploading")
        return SourceUploadTarget(
            id=source_id,
            storage_path=storage_path,
            upload_token="development-upload-token",
            status="uploading",
        )

    def complete_source(self, owner_id: UUID, source_id: UUID) -> SourceSummary:
        source = self._source_for_owner(owner_id, source_id)
        source.status = "uploaded"
        return SourceSummary(id=source.id, filename=source.filename, status="uploaded")

    def create_course(self, owner_id: UUID, request: CreateCourseRequest) -> CourseSummary:
        for source_id in request.source_ids:
            source = self._source_for_owner(owner_id, source_id)
            if source.status == "uploading":
                raise HTTPException(status_code=status.HTTP_409_CONFLICT, detail="Source upload is not complete.")
            if source.status == "failed":
                raise HTTPException(status_code=status.HTTP_409_CONFLICT, detail="Source ingestion failed.")

        now = datetime.now(UTC)
        course_id = uuid4()
        self.courses[course_id] = CourseRecord(
            id=course_id,
            owner_id=owner_id,
            title=request.title,
            goal=request.goal,
            source_ids=request.source_ids,
            status="draft",
            active_version=1,
            updated_at=now,
        )
        return self._summary(self.courses[course_id])

    def list_courses(self, owner_id: UUID) -> list[CourseSummary]:
        records = [record for record in self.courses.values() if record.owner_id == owner_id]
        return [self._summary(record) for record in sorted(records, key=lambda item: item.updated_at, reverse=True)]

    def get_course(self, owner_id: UUID, course_id: UUID) -> CourseSummary:
        return self._summary(self._course_for_owner(owner_id, course_id))

    def course_map(self, owner_id: UUID, course_id: UUID) -> CourseMapResponse:
        course = self._course_for_owner(owner_id, course_id)
        source_hash = sha256("".join(str(source_id) for source_id in course.source_ids).encode()).hexdigest()[:8]
        return CourseMapResponse(
            course_id=course.id,
            version=course.active_version,
            concepts=[
                CourseMapConcept(slug="source-orientation", title="Orient to the source", kind="conceptual", summary_markdown=f"A cited course map generated from source set `{source_hash}`."),
                CourseMapConcept(slug="core-pattern", title="Apply the core pattern", kind="coding", summary_markdown="The first coding lab will be generated by the lesson worker."),
                CourseMapConcept(slug="robustness", title="Verify robust behavior", kind="coding", summary_markdown="A later transfer task checks the idea in a fresh context."),
            ],
        )

    def course_progress(self, owner_id: UUID, course_id: UUID) -> CourseProgressResponse:
        course = self._course_for_owner(owner_id, course_id)
        source_count = len(course.source_ids)
        return CourseProgressResponse(
            course_id=course.id,
            stage="ready",
            sources_ready=source_count,
            sources_total=source_count,
            lessons_built=2,
            lessons_total=2,
        )

    def regenerate_course(self, owner_id: UUID, course_id: UUID) -> CourseSummary:
        return self._summary(self._course_for_owner(owner_id, course_id))

    def _source_for_owner(self, owner_id: UUID, source_id: UUID) -> SourceRecord:
        source = self.sources.get(source_id)
        if source is None or source.owner_id != owner_id:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Source not found.")
        return source

    def _course_for_owner(self, owner_id: UUID, course_id: UUID) -> CourseRecord:
        course = self.courses.get(course_id)
        if course is None or course.owner_id != owner_id:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Course not found.")
        return course

    @staticmethod
    def _summary(course: CourseRecord) -> CourseSummary:
        return CourseSummary(
            id=course.id,
            title=course.title,
            goal=course.goal,
            status=course.status,
            active_version=course.active_version,
            updated_at=course.updated_at,
        )


class SupabaseCourseRepository:
    """Server-side adapter that applies explicit owner filters even with a service key."""

    name = "supabase"

    def __init__(self, client: Client) -> None:
        self.client = client

    def create_source(self, owner_id: UUID, request: CreateSourceRequest) -> SourceUploadTarget:
        source_id = uuid4()
        safe_name = PurePosixPath(request.filename).name
        storage_path = f"{owner_id}/{source_id}/{safe_name}"
        self._data(
            self.client.table("source_documents").insert(
                {
                    "id": str(source_id),
                    "owner_id": str(owner_id),
                    "filename": safe_name,
                    "mime_type": request.mime_type,
                    "byte_size": request.byte_size,
                    "storage_path": storage_path,
                    "status": "uploading",
                }
            ),
            "create source",
        )
        try:
            signed_upload = self.client.storage.from_("sources").create_signed_upload_url(storage_path)
        except Exception as exc:
            self._delete_source(owner_id, source_id)
            logger.exception("Could not create a signed source upload URL")
            raise HTTPException(
                status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
                detail="A secure upload could not be prepared. Please try again.",
            ) from exc
        return SourceUploadTarget(
            id=source_id,
            storage_path=storage_path,
            upload_token=signed_upload["token"],
            status="uploading",
        )

    def complete_source(self, owner_id: UUID, source_id: UUID) -> SourceSummary:
        source = self._source_for_owner(owner_id, source_id)
        if source["status"] == "uploaded":
            return self._enqueue_source_ingestion(owner_id, source_id, source["filename"])
        if source["status"] in {"ingesting", "ready"}:
            return SourceSummary(id=source_id, filename=source["filename"], status=source["status"])
        if source["status"] != "uploading":
            raise HTTPException(status_code=status.HTTP_409_CONFLICT, detail="Source cannot be completed in its current state.")

        storage_path = PurePosixPath(source["storage_path"])
        objects = self._list_storage_objects(str(storage_path.parent), storage_path.name)
        uploaded_object = next((item for item in objects if item.get("name") == storage_path.name), None)
        if uploaded_object is None:
            raise HTTPException(status_code=status.HTTP_409_CONFLICT, detail="Source file upload could not be verified.")
        metadata = uploaded_object.get("metadata") or {}
        if self._stored_size(metadata) != source["byte_size"]:
            raise HTTPException(status_code=status.HTTP_409_CONFLICT, detail="Uploaded source size does not match the request.")
        stored_mime_type = metadata.get("mimetype")
        if stored_mime_type and stored_mime_type != source["mime_type"]:
            raise HTTPException(status_code=status.HTTP_409_CONFLICT, detail="Uploaded source type does not match the request.")

        self._data(
            self.client.table("source_documents")
            .update({"status": "uploaded", "updated_at": datetime.now(UTC).isoformat()})
            .eq("id", str(source_id))
            .eq("owner_id", str(owner_id)),
            "complete source",
        )
        return self._enqueue_source_ingestion(owner_id, source_id, source["filename"])

    def create_course(self, owner_id: UUID, request: CreateCourseRequest) -> CourseSummary:
        source_ids = list(dict.fromkeys(request.source_ids))
        source_rows: list[dict[str, Any]] = []
        if source_ids:
            source_rows = self._data(
                self.client.table("source_documents")
                .select("id,status")
                .eq("owner_id", str(owner_id))
                .in_("id", [str(source_id) for source_id in source_ids]),
                "validate course sources",
            )
        found_ids = {UUID(row["id"]) for row in source_rows}
        if found_ids != set(source_ids):
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Source not found.")
        if any(row["status"] == "uploading" for row in source_rows):
            raise HTTPException(status_code=status.HTTP_409_CONFLICT, detail="Source upload is not complete.")
        if any(row["status"] == "failed" for row in source_rows):
            raise HTTPException(status_code=status.HTTP_409_CONFLICT, detail="Source ingestion failed.")

        source_set_hash = sha256(":".join(sorted(str(source_id) for source_id in source_ids)).encode()).hexdigest()
        course_row = self._one(
            self._data(
                self.client.table("courses").insert(
                    {
                        "owner_id": str(owner_id),
                        "title": request.title,
                        "goal": request.goal,
                        "source_set_hash": source_set_hash,
                        "status": "draft",
                    }
                ),
                "create course",
            ),
            "Course",
        )
        course_id = UUID(course_row["id"])

        try:
            version_row = self._one(
                self._data(
                    self.client.table("course_versions").insert(
                        {"course_id": str(course_id), "version": 1, "status": "planning"}
                    ),
                    "create course version",
                ),
                "Course version",
            )
            self._data(
                self.client.table("courses")
                .update({"active_version_id": version_row["id"]})
                .eq("id", str(course_id))
                .eq("owner_id", str(owner_id)),
                "activate course version",
            )
            if source_ids:
                self._data(
                    self.client.table("course_sources").insert(
                        [
                            {
                                "course_id": str(course_id),
                                "source_document_id": str(source_id),
                                "position": position,
                            }
                            for position, source_id in enumerate(source_ids, start=1)
                        ]
                    ),
                    "attach course sources",
                )
            self._call(
                self.client.rpc(
                    "enqueue_course_planning",
                    {"p_course_id": str(course_id), "p_owner_id": str(owner_id)},
                ),
                "enqueue course planning",
            )
        except HTTPException:
            self._delete_course(owner_id, course_id)
            raise

        return CourseSummary(
            id=course_id,
            title=course_row["title"],
            goal=course_row["goal"],
            status="draft",
            active_version=1,
            updated_at=self._timestamp(course_row["updated_at"]),
        )

    def list_courses(self, owner_id: UUID) -> list[CourseSummary]:
        courses = self._data(
            self.client.table("courses")
            .select("id,title,goal,status,active_version_id,updated_at")
            .eq("owner_id", str(owner_id))
            .order("updated_at", desc=True),
            "list courses",
        )
        versions = self._versions_for([row["active_version_id"] for row in courses if row["active_version_id"]])
        return [self._summary(row, versions) for row in courses]

    def get_course(self, owner_id: UUID, course_id: UUID) -> CourseSummary:
        course = self._course_for_owner(owner_id, course_id)
        versions = self._versions_for([course["active_version_id"]] if course["active_version_id"] else [])
        return self._summary(course, versions)

    def course_map(self, owner_id: UUID, course_id: UUID) -> CourseMapResponse:
        course = self._course_for_owner(owner_id, course_id)
        version_id = course.get("active_version_id")
        if not version_id:
            raise HTTPException(status_code=status.HTTP_409_CONFLICT, detail="Course planning has not started.")
        version = self._one(
            self._data(
                self.client.table("course_versions")
                .select("id,version")
                .eq("id", version_id)
                .eq("course_id", str(course_id)),
                "load course version",
            ),
            "Course version",
        )
        concepts = self._data(
            self.client.table("concepts")
            .select("id,slug,title,kind")
            .eq("course_version_id", version_id)
            .order("slug"),
            "load course concepts",
        )
        summaries = self._summary_lookup([row["id"] for row in concepts])
        return CourseMapResponse(
            course_id=course_id,
            version=version["version"],
            concepts=[
                CourseMapConcept(
                    slug=row["slug"],
                    title=row["title"],
                    kind=row["kind"],
                    summary_markdown=summaries.get(row["id"], ""),
                )
                for row in concepts
            ],
        )

    def course_progress(self, owner_id: UUID, course_id: UUID) -> CourseProgressResponse:
        course = self._course_for_owner(owner_id, course_id)
        version_id = course.get("active_version_id")

        source_rows = self._data(
            self.client.table("course_sources").select("source_document_id").eq("course_id", str(course_id)),
            "load course sources",
        )
        source_ids = [row["source_document_id"] for row in source_rows]
        sources_total = len(source_ids)
        sources_ready = 0
        if source_ids:
            statuses = self._data(
                self.client.table("source_documents").select("status").in_("id", source_ids),
                "load source statuses",
            )
            sources_ready = sum(1 for row in statuses if row["status"] == "ready")

        if not version_id:
            return CourseProgressResponse(
                course_id=course_id, stage="planning",
                sources_ready=sources_ready, sources_total=sources_total,
                lessons_built=0, lessons_total=0,
            )

        version = self._one(
            self._data(
                self.client.table("course_versions").select("status").eq("id", version_id),
                "load course version status",
            ),
            "Course version",
        )
        version_status = version["status"]

        if version_status == "failed":
            return CourseProgressResponse(
                course_id=course_id, stage="failed",
                sources_ready=sources_ready, sources_total=sources_total,
                lessons_built=0, lessons_total=0,
            )

        if version_status in ("planning", "generating"):
            stage = "ingesting_sources" if sources_total > 0 and sources_ready < sources_total else "planning"
            return CourseProgressResponse(
                course_id=course_id, stage=stage,
                sources_ready=sources_ready, sources_total=sources_total,
                lessons_built=0, lessons_total=0,
            )

        coding_concepts = self._data(
            self.client.table("concepts")
            .select("id")
            .eq("course_version_id", version_id)
            .eq("kind", "coding"),
            "load coding concepts",
        )
        lessons_total = 0
        lessons_built = 0
        if coding_concepts:
            lesson_rows = self._data(
                self.client.table("lesson_definitions")
                .select("build_status")
                .eq("kind", "lesson")
                .in_("concept_id", [row["id"] for row in coding_concepts]),
                "load lesson build status",
            )
            lessons_total = len(lesson_rows)
            lessons_built = sum(1 for row in lesson_rows if row["build_status"] == "built")

        stage = "building_lessons" if lessons_total > 0 and lessons_built < lessons_total else "ready"
        return CourseProgressResponse(
            course_id=course_id, stage=stage,
            sources_ready=sources_ready, sources_total=sources_total,
            lessons_built=lessons_built, lessons_total=lessons_total,
        )

    def regenerate_course(self, owner_id: UUID, course_id: UUID) -> CourseSummary:
        self._course_for_owner(owner_id, course_id)
        self._call(
            self.client.rpc(
                "regenerate_course_planning",
                {"p_course_id": str(course_id), "p_owner_id": str(owner_id)},
            ),
            "regenerate course planning",
        )
        return self.get_course(owner_id, course_id)

    def _source_for_owner(self, owner_id: UUID, source_id: UUID) -> dict[str, Any]:
        return self._one(
            self._data(
                self.client.table("source_documents")
                .select("id,filename,mime_type,byte_size,storage_path,status")
                .eq("id", str(source_id))
                .eq("owner_id", str(owner_id)),
                "load source",
            ),
            "Source",
        )

    def _course_for_owner(self, owner_id: UUID, course_id: UUID) -> dict[str, Any]:
        return self._one(
            self._data(
                self.client.table("courses")
                .select("id,title,goal,status,active_version_id,updated_at")
                .eq("id", str(course_id))
                .eq("owner_id", str(owner_id)),
                "load course",
            ),
            "Course",
        )

    def _versions_for(self, version_ids: Sequence[str]) -> dict[str, int]:
        if not version_ids:
            return {}
        rows = self._data(
            self.client.table("course_versions").select("id,version").in_("id", list(version_ids)),
            "load course versions",
        )
        return {row["id"]: row["version"] for row in rows}

    def _summary_lookup(self, concept_ids: Sequence[str]) -> dict[str, str]:
        if not concept_ids:
            return {}
        rows = self._data(
            self.client.table("concept_summaries")
            .select("concept_id,summary_markdown")
            .in_("concept_id", list(concept_ids)),
            "load concept summaries",
        )
        return {row["concept_id"]: row["summary_markdown"] for row in rows}

    def _delete_course(self, owner_id: UUID, course_id: UUID) -> None:
        try:
            self.client.table("courses").delete().eq("id", str(course_id)).eq("owner_id", str(owner_id)).execute()
        except (APIError, HTTPError):
            logger.exception("Could not clean up failed course creation", extra={"course_id": str(course_id)})

    def _delete_source(self, owner_id: UUID, source_id: UUID) -> None:
        try:
            self.client.table("source_documents").delete().eq("id", str(source_id)).eq("owner_id", str(owner_id)).execute()
        except (APIError, HTTPError):
            logger.exception("Could not clean up failed source creation", extra={"source_id": str(source_id)})

    def _enqueue_source_ingestion(self, owner_id: UUID, source_id: UUID, filename: str) -> SourceSummary:
        self._call(
            self.client.rpc(
                "enqueue_source_ingestion",
                {"p_source_id": str(source_id), "p_owner_id": str(owner_id)},
            ),
            "enqueue source ingestion",
        )
        return SourceSummary(id=source_id, filename=filename, status="ingesting")

    def _list_storage_objects(self, folder: str, filename: str) -> list[dict[str, Any]]:
        try:
            return self.client.storage.from_("sources").list(folder, {"limit": 1, "search": filename})
        except Exception as exc:
            logger.exception("Could not verify a source upload in Storage")
            raise HTTPException(
                status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
                detail="The source upload could not be verified. Please try again.",
            ) from exc

    def _data(self, request: Any, action: str) -> list[dict[str, Any]]:
        try:
            return request.execute().data or []
        except (APIError, HTTPError) as exc:
            logger.exception("Supabase request failed while attempting to %s", action)
            raise HTTPException(
                status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
                detail="The course service is temporarily unavailable.",
            ) from exc

    @staticmethod
    def _call(request: Any, action: str) -> None:
        try:
            request.execute()
        except (APIError, HTTPError) as exc:
            logger.exception("Supabase request failed while attempting to %s", action)
            raise HTTPException(
                status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
                detail="The course service is temporarily unavailable.",
            ) from exc

    @staticmethod
    def _one(rows: list[dict[str, Any]], resource_name: str) -> dict[str, Any]:
        if not rows:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail=f"{resource_name} not found.")
        return rows[0]

    @staticmethod
    def _timestamp(value: str) -> datetime:
        return datetime.fromisoformat(value.replace("Z", "+00:00"))

    @staticmethod
    def _stored_size(metadata: dict[str, Any]) -> int | None:
        value = metadata.get("size")
        try:
            return int(value)
        except (TypeError, ValueError):
            return None

    @staticmethod
    def _summary(row: dict[str, Any], versions: dict[str, int]) -> CourseSummary:
        active_version_id = row.get("active_version_id")
        if not active_version_id or active_version_id not in versions:
            raise HTTPException(status_code=status.HTTP_409_CONFLICT, detail="Course version is unavailable.")
        return CourseSummary(
            id=UUID(row["id"]),
            title=row["title"],
            goal=row["goal"],
            status=row["status"],
            active_version=versions[active_version_id],
            updated_at=SupabaseCourseRepository._timestamp(row["updated_at"]),
        )


_memory_repository = MemoryCourseRepository()


def get_repository() -> CourseRepository:
    if get_settings().repository_backend == "supabase":
        return SupabaseCourseRepository(get_service_client())
    return _memory_repository
